
# version: "3.8"


services:
    api:
        build: ./api
        container_name: django_api
        ports:
            - "8000:8000"
        volumes:
            - ./api:/app
        depends_on:
            - db
        env_file:
            - .env # Load environment variables from .env file

    client:
        build: ./client
        container_name: react_client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: npm start
        depends_on:
            - api

    db:
        image: postgres:15
        container_name: postgres_db
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - .env # Load environment variables from .env file
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data:
