# Generated by Django 5.1.5 on 2025-02-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
