# Generated by Django 5.1.5 on 2025-02-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemlogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemLogs',
            new_name='SystemLog',
        ),
    ]
