# Generated by Django 5.1.5 on 2025-02-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
