# Generated by Django 5.1.5 on 2025-02-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_city_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
